### ISSUE TITLE
メモリオで地図？

### ISSUE THREAD

**Issue by suztomo** [suztomo/Memorio#107]
旅行で行く先に住んでいる人を一覧したい。アイコンを地図で表示してタップして、さらに「詳細」をタップしたらひとのページに遷移。

11月15日のメールより。

**Comment by suztomo** [comment]
2025年8月に試して見たけれども、地図の連携はなかなか難しい。

- google_maps_flutterは地図表示だけのライブらりでGeocoding(住所から座標を持ってくる). Bundle IDに制限がかかっているAPI keyは動いた。
- FlutterのgeocodingプラグインはiOSとAndroidに入っているネイティブのGeocoding機能を使う。ただ藤沢市の住所をなぜかニュージャージーだと認識するなど正確さがGoogle Mapsに劣る。
- Google Maps APIのAPI keyはbundle IDで制限を掛けられるけれども、geocodingのREST APIを使おうとしたら失敗した。これができちゃえばbundle IDの制限ないようなものだから。Geocodingがやりたければサーバーサイドでやらないといけない。
- ピンの画像を思った通りの大きさに表示するのは意外に面倒。
  ```
  // Load custom marker icon from assets and resize it properly
  Future<void> _loadCustomMarker() async {
    try {
      // Load image data
      final ByteData data = await rootBundle.load('assets/images/suztomo.png');
      
      // Decode and resize the image to 40x40 pixels
      final ui.Codec codec = await ui.instantiateImageCodec(
        data.buffer.asUint8List(),
        targetWidth: 40,
        targetHeight: 40,
      );
      
      final ui.FrameInfo frameInfo = await codec.getNextFrame();
      final ByteData? resizedData = await frameInfo.image.toByteData(format: ui.ImageByteFormat.png);
      
      if (resizedData != null) {
        _customMarkerIcon = BitmapDescriptor.fromBytes(resizedData.buffer.asUint8List());
        print('Successfully loaded and resized suztomo.png marker to 40x40');
      } else {
        throw Exception('Failed to resize image');
      }
    } catch (e) {
      print('Failed to load suztomo.png marker: $e');
      // Fallback to default marker with custom color
      _customMarkerIcon = BitmapDescriptor.defaultMarkerWithHue(BitmapDescriptor.hueRed);
    }
  }
  ```
- google_maps_flutterはホットリスタートをすると２回に１回失敗する。
  ```
  [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '0', null)
  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
  #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370:18)
  <asynchronous suspension>
  #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
  <asynchronous suspension>
  #3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:933:36)
  <asynchronous suspension>
  ```

```

  Set<Marker> _markers = {};
  bool _isLoading = true;
  BitmapDescriptor? _customMarkerIcon;

  @override
  void initState() {
    super.initState();
    _initializeMap();
  }
  
  Future<void> _initializeMap() async {
    await _loadCustomMarker();
    await _geocodeAddresses();
  }

  // Function to geocode an address using Google Geocoding API
  Future<LatLng?> _geocodeAddress(String address) async {
    try {
      final String encodedAddress = Uri.encodeComponent(address);
      final String url = 'https://maps.googleapis.com/maps/api/geocode/json?address=$encodedAddress&key=$_apiKey';
      
      print('=== GEOCODING DEBUG ===');
      print('Address: $address');
      print('Encoded: $encodedAddress');
      print('URL: $url');
      print('API Key starts with: ${_apiKey.substring(0, 10)}...');
      
      final response = await http.get(Uri.parse(url));
      
      print('Response status: ${response.statusCode}');
      print('Response body: ${response.body}');
      print('Response headers: ${response.headers}');
      
      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        print('Parsed JSON status: ${data['status']}');
        
        if (data['status'] == 'OK' && data['results'].isNotEmpty) {
          final location = data['results'][0]['geometry']['location'];
          final coordinates = LatLng(location['lat'], location['lng']);
          
          print('SUCCESS: $address -> $coordinates');
          return coordinates;
        } else {
          print('API ERROR Status: ${data['status']}');
          if (data['error_message'] != null) {
            print('API ERROR Message: ${data['error_message']}');
          }
          print('Full response: $data');
        }
      } else {
        print('HTTP ERROR: ${response.statusCode}');
        print('HTTP ERROR Body: ${response.body}');
      }
    } catch (e, stackTrace) {
      print('EXCEPTION: $e');
      print('Stack trace: $stackTrace');
    }
    
    print('=== GEOCODING FAILED ===');
    return null;
  }


  // Get custom marker icon for each location
  BitmapDescriptor _getMarkerIcon(int index, String address) {
    // Use suztomo.png for all markers
    return _customMarkerIcon ?? BitmapDescriptor.defaultMarkerWithHue(BitmapDescriptor.hueBlue);
  }

  // Geocode all addresses and create markers
  Future<void> _geocodeAddresses() async {
    Set<Marker> newMarkers = {};
    
    for (int i = 0; i < _addresses.length; i++) {
      final address = _addresses[i];
      final coordinates = await _geocodeAddress(address);
      
      if (coordinates != null) {
        newMarkers.add(
          Marker(
            markerId: MarkerId('location_$i'),
            position: coordinates,
            icon: _getMarkerIcon(i, address),
            infoWindow: InfoWindow(
              title: address,
              snippet: 'Lat: ${coordinates.latitude.toStringAsFixed(4)}, Lng: ${coordinates.longitude.toStringAsFixed(4)}',
            ),
          ),
        );
        print('Geocoded $address: ${coordinates.latitude}, ${coordinates.longitude}');
      }
    }

    setState(() {
      _markers = newMarkers;
      _isLoading = false;
      print('Created ${_markers.length} markers');
      for (final marker in _markers) {
        print('Marker ${marker.markerId.value} at ${marker.position}');
      }
    });
    
    // Auto-fit markers in view after a longer delay to ensure map is ready
    if (_markers.isNotEmpty) {
      print('Waiting for map to be ready before fitting bounds...');
      await Future.delayed(const Duration(milliseconds: 1500));
      await _fitMarkersInView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _isLoading
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 16),
                  Text('Geocoding addresses...'),
                ],
              ),
            )
          : GoogleMap(
              mapType: MapType.normal,
              initialCameraPosition: _initialPosition,
              markers: _markers,
              onMapCreated: (GoogleMapController controller) {
                _controller.complete(controller);
                print('Google Map created successfully');
              },
            ),
      floatingActionButton: _isLoading
          ? null
          : FloatingActionButton.extended(
              onPressed: _fitMarkersInView,
              label: const Text('Show all locations'),
              icon: const Icon(Icons.zoom_out_map),
            ),
    );
  }

  // Function to fit all markers in view
  Future<void> _fitMarkersInView() async {
    if (_markers.isEmpty) {
      print('No markers to fit');
      return;
    }
    
    try {
      final GoogleMapController controller = await _controller.future;
      
      // Calculate bounds for all markers
      double minLat = _markers.first.position.latitude;
      double maxLat = _markers.first.position.latitude;
      double minLng = _markers.first.position.longitude;
      double maxLng = _markers.first.position.longitude;
      
      for (final marker in _markers) {
        minLat = math.min(minLat, marker.position.latitude);
        maxLat = math.max(maxLat, marker.position.latitude);
        minLng = math.min(minLng, marker.position.longitude);
        maxLng = math.max(maxLng, marker.position.longitude);
      }
      
      // Add some padding to the bounds
      final double latPadding = (maxLat - minLat) * 0.2; // 20% padding
      final double lngPadding = (maxLng - minLng) * 0.2; // 20% padding
      
      minLat -= latPadding;
      maxLat += latPadding;
      minLng -= lngPadding;
      maxLng += lngPadding;
      
      print('Fitting bounds with padding: SW(${minLat}, ${minLng}) to NE(${maxLat}, ${maxLng})');
      
      // Create bounds and animate camera
      final LatLngBounds bounds = LatLngBounds(
        southwest: LatLng(minLat, minLng),
        northeast: LatLng(maxLat, maxLng),
      );
      
      await controller.animateCamera(CameraUpdate.newLatLngBounds(bounds, 50));
      print('Camera animation completed');
    } catch (e) {
      print('Error fitting markers in view: $e');
    }
  }
```

<img width="750" height="1334" alt="Image" src="https://github.com/user-attachments/assets/df548490-507d-434d-ba33-e7207696edf6" />

**Comment by suztomo** [comment]
とある推し活アプリのスクリーンショット

![image](https://github.com/user-attachments/assets/42753008-5cb3-4544-940a-f973027315d7)
