### ISSUE TITLE
The Scrollbar's ScrollController has no ScrollPosition attached.

### ISSUE THREAD

**Issue by suztomo** [suztomo/Memorio#92]
Scrollbarの使い方が変わった？

```
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: The Scrollbar's ScrollController has no ScrollPosition attached.
flutter: A Scrollbar cannot be painted without a ScrollPosition.
flutter: The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
flutter: associated with the ScrollView that the Scrollbar is being applied to. A ScrollView with an
flutter: Axis.vertical ScrollDirection will automatically use the PrimaryScrollController if the user has not
flutter: provided a ScrollController, but a ScrollDirection of Axis.horizontal will not. To use the
flutter: PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1285:9)
flutter: #1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1310:6)
flutter: #2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
flutter: #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
flutter: #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
flutter: #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:611:12)
flutter: #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:462:12)
flutter: #8      RawScrollbarState._handleScrollNotification (package:flutter/src/widgets/scrollbar.dart:1567:37)
flutter: #9      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
flutter: #10     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
flutter: #11     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
flutter: #12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4133:39)
flutter: #13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
flutter: #14     DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:465:139)
flutter: #15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:899:15)
flutter: #16     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:279:9)
flutter: #17     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
flutter: #18     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
flutter: #19     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
flutter: #20     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:647:12)
flutter: #21     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
flutter: #22     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
flutter: #23     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
flutter: #24     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
flutter: #25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
flutter: #26     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
flutter: #27     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
flutter: #28     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
flutter: #29     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
flutter: #30     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
flutter: #31     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
flutter: #32     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
flutter: #33     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
flutter: #34     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
flutter: #35     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
flutter: #36     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
flutter: #40     _invoke1 (dart:ui/hooks.dart:185:10)
flutter: #41     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
flutter: #42     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
flutter: (elided 3 frames from dart:async)
```

**Comment by suztomo** [comment]
Scrollbarにcontrollerを指定したら直った。中に入っているListView.Builderと同じcontroller.
